source 'https://rubygems.org'

gem 'rails', '~> 3.2.0'
gem 'sqlite3'

# gem 'listen'
gem 'rb-inotify', :require => false  # linux
gem 'rb-fsevent', :require => false  # mac os x
gem 'rb-kqueue',  :require => false  # bsd

group :test do
  if ENV['SPRING_TEST_WITH_RSPEC']
    gem 'rspec'
    gem 'rspec-rails'
  end
end
